### ISSUE TITLE
Modules don't support the same variables as the equivalent lookups

### ISSUE THREAD

**Issue by DerEnderKeks** [ansible-collections/community.hashi_vault#354]
##### SUMMARY

Modules don't support the same variables as the equivalent lookups. 

E.g. the `vault_kv2_get` module doesn't support the `ansible_hashi_vault_url` variable that the `vault_kv2_get` lookup understands. This means that you have to set the parameters for the tasks that use the modules, while the lookup works just fine with the global variables.

At least the following are affected, but probably others too: `vault_kv2_get`, `vault_write_lookup`, `vault_list`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vault_*

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.3]
  config file = /home/redacted/awx/ansible.cfg
  configured module search path = ['/home/redacted/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/redacted/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/redacted/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/redacted/.local/bin/ansible
  python version = 3.10.10 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/redacted/.local/lib/python3.10/site-packages/ansible_collections
Collection            Version
--------------------- -------
community.hashi_vault 4.1.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Rocky Linux 9

##### STEPS TO REPRODUCE

1. Try to use one of the modules while the variables supported by the equivalent lookup are set
2. Notice the error because of missing parameters like `url` or `token`

##### EXPECTED RESULTS

The modules should support the exact same variables as the lookups

##### ACTUAL RESULTS

The modules don't support the same variables as the lookups

**Comment by briantist** [comment]
Hi @DerEnderKeks ! This is the same issue described here:
- #327 

It's a limitation of Ansible itself, and we have a plugin in the collection that can be used to help with this, there's some details in the linked issue.

If you still have further questions, let me know in the comments of either this issue or that other issue.

**Comment by DerEnderKeks** [comment]
Thanks for the quick reply! 
Is there a good way to use the settings lookup across multiple plays? I currently already have a role to login to vault once, which I just include as a role dependency in other roles. Could I integrate setting the variables there somehow? As far as I can tell I would have to set the module defaults at least in every play that I use vault..

**Comment by briantist** [comment]
@DerEnderKeks this is another limitation in Ansible that I don't have a way around. As you correctly pointed out, you'll have to set the defaults at least once per play.

If you're using a new enough ansible-core, it can help at least to set it at the group level, using [the form in the first example here](https://docs.ansible.com/ansible/devel/collections/community/hashi_vault/vault_ansible_settings_lookup.html#examples):

```yaml
- hosts: all
  vars:
    ansible_hashi_vault_auth_method: token
  module_defaults:
    group/community.hashi_vault.vault: "{{ lookup('community.hashi_vault.vault_ansible_settings') }}"
  tasks:
```

Another way to have modules use the plugin vars is to create action plugins for them, but I didn't do that for a few reasons:
* there's not really a good supported way to have a single action plugin work for all the modules, without having to write separate plugins for each one
* It adds testing complexity and testing maintenance
* Using variables and settings from the controller is often _not_ desired if you're actually running the modules on remote hosts, so this should be an explicit choice, and where possible I prefer that choice to be made in a way that idiomatic to ansible (choice could be done via module parameters, but that's not typical)

I think in theory, you could create your own action plugin that did this for particular modules, and have it call to actual modules for implementation, if you felt the trade-off was worth it for your situation.

Unlike a collection-wide version, you'd be able to simplify a lot of the choices because you don't have to account for varied uses and can focus on only your own.

But personally I'd probably resign to repeating the `module_defaults` block; if you use the action group it's only two lines, and you already have to add `hosts:` and `tasks:` or `roles:` to other plays anyway.
