### ISSUE TITLE
Feature Request: Add support for azure auth method

### ISSUE THREAD

**Issue by jghal** [ansible-collections/community.hashi_vault#78]
We deploy to both AWS and Azure, and are adding HashiCorp Vault to provide a cloud-agnostic secrets management solution. I was just testing out this collection on AWS and the `aws_iam_login` auth method works great. Vault supports a similar [azure](https://www.vaultproject.io/docs/auth/azure) auth method for Azure that uses the instances [Managed Service Identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview) (MSI).

It would be great to have the `azure` auth method supported by this collection,

**Comment by briantist** [comment]
Hi @jghal ! I thought I had left a comment already and am just realizing now I didn't, so I apologize for the long delay!

Azure auth method would be great to add; the primary difficulty is that we cannot fully test it against Azure as we don't have that in CI.

I'll also add that a [refactor project](https://github.com/ansible-collections/community.hashi_vault/projects/4) is underway to move auth methods into dedicated module_utils, where they can be shared with the existing plugin and any future plugins. 

A major milestone is hopefully close to being merged (#113), and looking at that might give you some idea how much easier it will be to add a new auth method soon.

As part of that project I expect to write better documentation on contributing new auth methods as well.

For integration testing on trickier auth methods like this that have external dependencies, I am also considering adding support in the tests/CI for mocking certain Vault server responses, so that we can test our end of the Vault backends without having to actually configure Vault to talk to those backends. But this is just in an "idea" stage for the time being.

If you're interested in contributing let me know!

---

As a possible workaround, since Azure auth is based on JWT, you may be able to use the generic JWT/OIDC auth method currently available in this plugin, to authenticate against Azure, but I don't have specifics on it.

**Comment by briantist** [comment]
Hi @jghal , I wanted to post an update letting you know that much of the above work is complete, and it would be a great time if you had any interest in contributing the `azure` auth method.

[I've just published some guidance on that here](https://community-hashi-vault-main.surge.sh/collections/community/hashi_vault/docsite/contributor_guide.html#contributing-auth-methods).

Since we won't be able to do a real integration with Azure for the tests, the MMock method described there could be used for this.

Of course I understand it's been a while, you may not even need this anymore, or may not be able to contribute.

---

At the least, if you've got a working setup with Vault and Azure, you could really help us out by giving samples of the API responses for successful and unsuccessful authentication attempts.

For example, `vault login -format=json -method=azure` (plus any additional params you need for a successful login) would give you a result you can post here; **of course you will need to sanitize it by removing anything sensitive**. We don't need a real token, or policies, or user names, you can even change the UUIDs making up the request ID and such.

Another result with a failed login of some kind would also be needed so that we can simulate that failure in our tests.

To give an idea what this output looks like, have a look at the other fixtures here: https://github.com/ansible-collections/community.hashi_vault/tree/main/tests/unit/plugins/module_utils/authentication/fixtures

We only need valid JSON; pretty-print formatting not required.

**Comment by jghal** [comment]
I still think it's a worthwhile feature to add, but my organization has moved away in favor of using the cloud-native secrets platforms directly so I don't have an environment to gather information anymore.

**Comment by briantist** [comment]
That makes sense @jghal , thanks for following up!

**Comment by jchenship** [comment]
I made a pull request here https://github.com/ansible-collections/community.hashi_vault/pull/293, the only thing I'm not sure is how to write and run unit tests, if anyone could help me a bit on that it will be great
