### ISSUE TITLE
hashi_vault should support secret v2 path (without adding /data/)

### ISSUE THREAD

**Issue by dr4Ke** [ansible-collections/community.hashi_vault#9]
##### SUMMARY

The `hashi_vault` lookup currently needs to use an API path to kv_v2 secrets. It would be nice to drop this requirement, like terraform do.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

hashi_vault

##### ADDITIONAL INFORMATION

The current call:
```yaml
- name: get secret (currently)
  debug:
    msg: "{{ lookup('hashi_vault', 'engine/path/data/secret/path`) }}"
```

The wanted call:
```yaml
- name: get secret (wanted)
  debug:
    msg: "{{ lookup('hashi_vault', 'engine/path/secret/path`) }}"
```

In the terraform provider, they [get the engine path](https://github.com/terraform-providers/terraform-provider-vault/blob/61bd17181d12d43433be914cb015dc2d169fd574/vault/kv_helpers.go#L88) from a call to `/v1/sys/internal/ui/mounts/{{ FULL_SECRET_PATH }}`.

**Comment by dmsimard** [comment]
Hi @dr4Ke, just FYI we've moved this issue to https://github.com/ansible-collections/community.hashi_vault

**Comment by synergiator** [comment]
Additionally, it should be possible to access a previous version:

```
vault kv get -version=1 secret/foo
```

Side note: is it actually possible to use lookup for v2 secrets? can't read this from the above

**Comment by briantist** [comment]
It's been a long time since this was opened, and the plugin has since been split off into its own (this) collection. So I want to give an update on what I've been thinking about regarding this request.

My thinking at the moment is that we're going to move toward adding more plugins and even modules, which will largely share functionality related to auth and connection.

The `hashi_vault` plugin is a little strange in that it's a generic "read" plugin for Vault; it can be used to (basically) read any path, but it also has some processing that's rather specific to the generic key/value backend (like dereferencing the return structure by default).

My current loose plan is to create new plugins that kind of "do one thing" and so that would likely mean separating the "just read without inferring anything" and the "retrieve a `kv` secret specifically" operations.

The way I see that working is that new plugins will come out for this stuff with clearer definition about what they do. The functionality of not needing `/data/` and of requesting a specific version (@synergiator this should be a new feature request I think, but what I'm writing here applies equally to that) are both specific to kv2, for example, and so those would be features in a plugin dedicated to retrieving kv secrets.

Once the [refactor project](https://github.com/ansible-collections/community.hashi_vault/projects/4) reaches critical mass I expect the rollout of new content to come pretty rapidly, as most of the code in the current plugin is around auth methods and will be centralized and shareable.

**Comment by briantist** [comment]
@dr4Ke and anyone else who may be subscribed or interested: please have a look at an open discussion about how to format paths for kv-focused plugins:
- #229

**Comment by briantist** [comment]
Implemented in:
- #246
