### ISSUE TITLE
Add  ansible_hashi_vault_token_file and ansible_hashi_vault_token_path variables

### ISSUE THREAD

**Issue by danielmotaleite** [ansible-collections/community.hashi_vault#94]
##### SUMMARY
Add variables equivalent to ANSIBLE_HASHI_VAULT_TOKEN_FILE and ANSIBLE_HASHI_VAULT_TOKEN_PATH, as it allow one to change this based in inventory settings

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
hashi_vault.py

##### ADDITIONAL INFORMATION
With https://github.com/ansible-collections/community.hashi_vault/issues/15
we get environment for setting vault token path and file, this is just expand their support for ansible variable

**Comment by briantist** [comment]
Hi @danielmotaleite thanks! This is related to #86 . I didn't add variables for everything at once, in order to scope the change down a bit, and I was trying to directly address the most important ones that pertained to #49 .

But It makes sense to add vars for these too. I'll look at getting those in place soon, likely in time for the 1.2.0 release.
